### PR TITLE
enhancement: validators struct separated

### PR DESCRIPTION
**Pull request by ajansari95**
Fixes QCK-285

- Perf improvement for zones struct
- separate out validators struct
- lookup for validators based on chain-id

### CODE REVIEW

**Comment by ajansari95** [comment]
testing suite setup needs to be fixed tests failing

**Comment by joe-bowman** [comment]
Would this be more performant to store each validator under it's own key. We do a bunch of operations on single validators, and fetching the entire valset for each is counterintuitive there. We can still fetch all validators for a chain by prefixing the key with the chain-id (make key chain-id + validatorbytes (not bech32 prefixed address, because 51 bytes vs 20 bytes))

**Comment by aljo242** [comment]
Make sure to run https://github.com/ingenuity-build/quicksilver/pull/389 targets once merged

**Comment by joe-bowman** [comment]
Closing in favour of #398

**Pull request closed without merging**
