### PR TITLE
Add last_redemption_rate to RegisteredZone

### PR DESCRIPTION
**Pull request by zanicar**
Solves #60 and #61

### CODE REVIEW

**Review by joe-bowman — APPROVED** [review]
lgtm

**Review by joe-bowman — CHANGES_REQUESTED** [review]
need to set the value of last_redemption_rate to 1.0 in msg_server (when zone is created)

**Comment by zanicar** [comment]
Thanks for the catch, updated.
0.95 - don't think that is necessary, as epoch 0 will present a zero-sum game, so no incentive to attack.

**Comment by joe-bowman** [comment]
> 0.95 - don't think that is necessary, as epoch 0 will present a zero-sum game, so no incentive to attack.

I think you are right. If anything the user loses out (zero rewards earned) and the pool benefits (earns rewards for that time period).

**Review by joe-bowman — APPROVED** [review]
lgtm

**Pull request merged**
