### PR TITLE
test: e2e environment additions

### PR DESCRIPTION
**Pull request by aljo242**
## 1. Summary

Fixes QCK-211

## 2.Type of change

- [X] New feature (non-breaking change which adds functionality)

## 3. Implementation details

- add `icq` relayer container and init script for setup
- add `xcc` container and init script for setup
- additional debug logging
- 
## 4. How to test/use

- `make test-e2e-debug`

### CODE REVIEW

**Comment by aljo242** [comment]
Lint is failing for unrelated warnings

**Review by joe-bowman — APPROVED** [review]
Lgtm

**Review by ajansari95 — COMMENTED** [review]
We should use custom build hermes version? Thoughts @joe-bowman @aljo242 ?

**Comment by aljo242** [comment]
> We should use custom build hermes version? Thoughts @joe-bowman @aljo242 ?

Yeah - I went ahead and made this change: https://github.com/ingenuity-build/quicksilver/pull/355/commits/b7d7fdf86d6f480c2a9ea5ec3b21b9b0312bcd15

**Review by ajansari95 — APPROVED** [review]
LGTM

**Review by joe-bowman — APPROVED** [review]
lgtm

**Pull request merged**
