### PR TITLE
test: interchaintest

### PR DESCRIPTION
**Pull request by aljo242**
Fixes QCK-213

To test:

`make ictest-all`

### CODE REVIEW

**Review by joe-bowman — APPROVED** [review]
lgtm

**Review by ajansari95 — APPROVED** [review]
lgtm

**Comment by aljo242** [comment]
Fixed a vulnerability picked up by `govulncheck`

**Review by ajansari95 — APPROVED** [review]
lgtm

**Comment by faddat** [comment]
I also wanted to voice my support of these changes.  

ICT is excellent.

**Review by joe-bowman — APPROVED** [review]
Lgtm

**Pull request merged**
