### PR TITLE
gitpod: use notional labs dev env

### PR DESCRIPTION
**Pull request by faddat**
This .gitpod.yml file uses a docker container that we build every hour as its development environment.  This mirrors how we run machines in prod.

### CODE REVIEW

**Comment by joe-bowman** [comment]
Hey Jacob, sorry for the delay on getting this merged - what exactly does this do?

**Comment by faddat** [comment]
ah hey Joe!

This is a combined go and rust development environment that uses https://gitpod.io

it gives us a single button to click, that checks out the repo on a PR or branch, and opens a dev env in a browser.

**Comment by joe-bowman** [comment]
Hey Jacob; can you let me know if anything needs updating here, or whether it is gtg?

**Comment by faddat** [comment]
hey, I think this can actually be closed -- long story short, we've moved away from gitpod.

Cheers!

-Jacob

**Pull request closed without merging**
