### PR TITLE
refactor: memo parsing logic in `ibc_packet_handlers.go`

### PR DESCRIPTION
**Pull request by aljo242**
## 1. Summary

refactor duplicated logic in `x/interchainstaking/keeper/ibc_packet_handlers.go` into a `types` package.

## 2.Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## 3. Implementation details

- Refactor duplicated code into `types` package
- add tests
- add fuzz tests

## 4. How to test/use

To run the fuzz test:

```
go test -fuzz=FuzzParseMsgMemo github.com/ingenuity-build/quicksilver/x/interchainstaking/types -fuzztime=5m 
```

## 5. Checklist

- [ ] Does the Readme need to be updated?

### CODE REVIEW

**Review by joe-bowman — COMMENTED** [review]
Looks good overall, but as discussed there seems to be no difference between the fuzz test and the unit test here in terms of coverage. As fuzz tests are not currently run on every push, and the unit test is not resource intensive, should be just keep that?

**Comment by ajansari95** [comment]
> Looks good overall, but as discussed there seems to be no difference between the fuzz test and the unit test here in terms of coverage. As fuzz tests are not currently run on every push, and the unit test is not resource intensive, should be just keep that?

i think we can add a fuzz test target in make file and not include in coverage?

**Review by joe-bowman — APPROVED** [review]
lgtm

**Review by ajansari95 — APPROVED** [review]
LGTM

**Pull request merged**
