### PR TITLE
V046 responses fix

### PR DESCRIPTION
**Pull request by joe-bowman**
## 1. Summary
Fixes v0.46 MsgResponses unmarshalling.

## 2.Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 3. Implementation details

Use any.GetValue() + proto.Unmarshal() instead of trying to unpack type without appropriate interface. 

## 4. How to test/use

Added v45 and v46 response unmarshalling tests.

### CODE REVIEW

**Review by ajansari95 — APPROVED** [review]
LGTM

**Comment by joe-bowman** [comment]
Tests are passing, but failing vulnchecker on go1.19 vulns; we can ignore these for this release. Bump to v1.20 needs sufficient testing to ensure determinism

**Comment by ajansari95** [comment]
> Tests are passing, but failing vulnchecker on go1.19 vulns; we can ignore these for this release. Bump to v1.20 needs sufficient testing to ensure determinism

agreed

**Review by ajansari95 — APPROVED** [review]
LGTM

**Review by prakritimalik — APPROVED** [review]
lgtm

**Pull request merged**
