### PR TITLE
docs: fix mint spec

### LINKED ISSUE #288: Update `x/mint` module spec
Context: https://github.com/ingenuity-build/quicksilver/tree/main/x/mint/spec

The current spec `README` contains information about osmosis and OSMO tokens.  Credit should still be given to osmosis, but the contents can be modified a bit more to be specific for quicksilver and QCK.

### LINKED ISSUE #315: Fix `x/mint` spec
The mint [spec](https://github.com/ingenuity-build/quicksilver/tree/main/x/mint/spec) is from when the code was extracted from Osmosis.  We should rewrite so that it is specific for quicksilver.

### PR DESCRIPTION
**Pull request by aljo242**
## 1. Summary
Fixes #288

## 2.Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] This change requires a documentation update

## 3. Implementation details

- refactor the `x/mint/spec` directory into a new `x/mint/README.md` file that contains all information
- remove all information that was related to osmosis
- add info

### CODE REVIEW

**Review by joe-bowman — APPROVED** [review]
looks good; will need to remember to update the bottom section when we update mainnet inflationary params.

**Review by joe-bowman — DISMISSED** [review]
lgtm

**Review by ajansari95 — COMMENTED** [review]
LGTM

**Review by joe-bowman — APPROVED** [review]
lgtm

**Comment by joe-bowman** [comment]
@ajansari95 - yours review was dismissed as stale; please rereview

**Review by ajansari95 — APPROVED** [review]
LGTM

**Pull request merged**
